"""Add problem_statement to Session model

Revision ID: bfc19190708a
Revises: d254cd2bbd87
Create Date: 2025-04-13 14:34:12.137303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc19190708a'
down_revision: Union[str, None] = 'd254cd2bbd87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column as nullable initially
    op.add_column('sessions', sa.Column('problem_statement', sa.Text(), nullable=True))
    # Step 2: Update existing rows with a default value
    op.execute("UPDATE sessions SET problem_statement = 'Default Problem Statement' WHERE problem_statement IS NULL")
    # Step 3: Alter the column to be non-nullable
    op.alter_column('sessions', 'problem_statement', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'problem_statement')
    # ### end Alembic commands ###
